spring.application.name=MindTrail
spring.data.mongodb.database=mindtraildb
spring.data.mongodb.uri=mongodb+srv://${ATLAS_USERNAME}:${ATLAS_PASSWORD}@cluster0.9ljryve.mongodb.net/?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# Mail server settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Your email credentials
spring.mail.username=${USERMAIL}
spring.mail.password=${PASSWORD}

# SMTP properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true