spring.application.name=MindTrail
spring.data.mongodb.database=mindtraildb
spring.data.mongodb.host=localhost
spring.data.mongodb.auto-index-creation=true

# Mail server settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Your email credentials
spring.mail.username=mindloop002@gmail.com
spring.mail.password=lypaapqgpvrguzep

# SMTP properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true